import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/Nav";
import localFont from 'next/font/local'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ADLaMDisplay = localFont({src : '../fonts/ADLaMDisplay-Regular.ttf'})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-primary">
        <main className={ADLaMDisplay.className}>
          <Nav />
          {children}
        </main>
      </body>
    </html>
  );
}
